
define(function (require, exports, module) {
    "use strict";

    var CommandManager = brackets.getModule("command/CommandManager"),
        Menus          = brackets.getModule("command/Menus"),
        EditorManager  = brackets.getModule("editor/EditorManager");
    var Dialogs        = brackets.getModule('widgets/Dialogs');

    var bootstrapVER = "3.3.6";
    var jqueryVER = "2.2.3";
    
    
    // Function to run when the menu item is clicked
    function InJector_HTML() {
          
      var editor = EditorManager.getCurrentFullEditor();
      if (editor) {
        var insertionPos = editor.getCursorPos();
        editor.document.batchOperation(function () {
        var htmlcontent =  '<!DOCTYPE html>\n<html>\n'+
        '<head>\n'+
        '<meta charset="utf-8">\n'+
        '<meta http-equiv="X-UA-Compatible" content="IE=edge">\n'+
        '<meta name="viewport" content="width=device-width, initial-scale=1">\n'+
        '<meta name="description" content="">\n'+
        '<meta name="author" content="">\n\r'+
        '<title>HTML 5</title>\n\r'+
 
        '<!-- Chrome on Android -->\n'+
        '<meta name="mobile-web-app-capable" content="yes">\n'+
        '<meta name="application-name" content="CHANGE-ME">\n'+
        '<link rel="icon" sizes="192x192" href="images/touch/chrome-touch-icon.png">\n'+
        
        '<!-- Safari on iOS -->\n'+
        '<meta name="apple-mobile-web-app-capable" content="yes">\n'+
        '<meta name="apple-mobile-web-app-status-bar-style" content="black">\n'+
        '<meta name="apple-mobile-web-app-title" content="CHANGE-ME">\n'+
        '<link rel="apple-touch-icon" href="images/touch/apple-touch-icon.png">\n'+   

        '</head>\n'+
        '<body>\n\r'+
        '<div>\n'+
        '<h3>This content was generated by the quickJect extension</h3>\n'+
        '</div>\n\r'+
        '</body>\n'+
        '</html>';
          editor.document.replaceRange(htmlcontent, insertionPos);
        });
      }
 
    }
    /*jQuery @ CloudFlare CDN */
    function InJector_jquery(){
      var editor = EditorManager.getCurrentFullEditor();
      if (editor) {
        var insertionPos = editor.getCursorPos();
        editor.document.batchOperation(function () {
        var jquerycontent =  '<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/'+jqueryVER+'/jquery.min.js"></script>\n'+
        '<script type="text/javascript">\n\r'+
        '$("document").ready(function(){\n\r'+
        '//Your code here\n\r'+'});\n\r </script>';
          editor.document.replaceRange(jquerycontent, insertionPos);
        });
      } 
    }
    
    function InJector_bootstrapCSS(){
         var editor = EditorManager.getCurrentFullEditor();
         if (editor) {
            var insertionPos = editor.getCursorPos();
            editor.document.batchOperation(function () {
            var bootstrapCSS='<link href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/'+bootstrapVER+'/css/bootstrap.min.css" rel="stylesheet" type="text/css" />\n'+
            '<link href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/'+bootstrapVER+'/css/bootstrap.min.css.map" rel="stylsheet" type="text/css" />\n'+ 
            '<link href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/'+bootstrapVER+'/css/bootstrap-theme.min.css" rel="stylesheet" type="text/css" />\n'+
            '<link href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/'+bootstrapVER+'/css/bootstrap-theme.min.css.map" rel="stylesheet" type="text/css" />\n';   
            editor.document.replaceRange(bootstrapCSS, insertionPos);  
            });
         }
     }
    
    function InJector_bootstrapJS(){
         var editor = EditorManager.getCurrentFullEditor();
         if (editor) {
            var insertionPos = editor.getCursorPos();
            editor.document.batchOperation(function () {
            var bootstrapJS= '<script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/'+bootstrapVER+'/js/bootstrap.min.js">\n';     
            editor.document.replaceRange(bootstrapJS, insertionPos);  
            });
         }
     }
    
    function InJector_AngularJS(){
         var editor = EditorManager.getCurrentFullEditor();
         if (editor) {
            var insertionPos = editor.getCursorPos();
            editor.document.batchOperation(function () {
            var angularJS= '<script src="https://cdnjs.cloudflare.com/ajax/libs/angular.js/1.5.5/angular.min.js">\n';     
            editor.document.replaceRange(angularJS, insertionPos);  
            });
         }
     }
    

      function InJector_css(){
       var editor = EditorManager.getCurrentFullEditor();
      if (editor) {
        var insertionPos = editor.getCursorPos();
        editor.document.batchOperation(function () {
        var csscontent =  'html, body, div, span, applet, object, iframe,h1, h2, h3, h4, h5, h6, p, blockquote, pre,a, abbr, acronym, address,'+
        'big, cite, code,del, dfn, em, img, ins, kbd, q, s, samp,small, strike, strong, sub, sup, tt, var,b, u, i, center,dl, dt, dd, ol, ul,'+ 'li,fieldset, form, label, legend,table, caption, tbody, tfoot, thead, tr, th, td,article, aside, canvas, details, embed,figure, figcaption,'+ 'footer, header, hgroup,menu, nav, output, ruby, section, summary,time, mark, audio, video '+
'{margin: 0;padding: 0;border: 0;font-size: 100%;font: inherit;vertical-align: baseline;}article, aside, details, figcaption, figure,footer,'+
'header, hgroup, menu, nav, section {display: block;}body {line-height: 1;}ol, ul'+
'{list-style: none;}blockquote, q {quotes: none;}blockquote:before, blockquote:after,q:before, q:after {content: "";content: none;}'+
'table {border-collapse: collapse;border-spacing: 0;}';
          editor.document.replaceRange(csscontent, insertionPos);
        });
      } 
    }
    
    function InJector_about(){
        var messageabout = 'InJector Generator<br>'+'Description:Quick inject HTML5 starter or Jquery, Bootstrap, Angular and more into your Brackets documents<br>'+
            'Author: Gerd Suhr <br>HomePage: <a title="https://github.com/Jighead/Brackets-InJector/" href="https://github.com/Jighead/Brackets-InJector/">Brackets-InJector</a>';
        Dialogs.showModalDialog('a',"About Extension",messageabout);
    }

    var ij_HTML = "htmlskeleton.quickject";
    CommandManager.register("HTML5", ij_HTML, InJector_HTML);
    
    var ij_JQUERY = "jqueryskeleton.quickject";
    CommandManager.register("CloudFlare jQuery", ij_JQUERY, InJector_jquery);
    
    var ij_BOOTSTRAPcs = "boostrapcssskeleton.quickject";
    CommandManager.register("CloudFlare BootStrap CSS", ij_BOOTSTRAPcs, InJector_bootstrapCSS);
    
    var ij_BOOTSTRAPjs = "bootstrapjsskeleton.quickject";
    CommandManager.register("CloudFlare BootStrap JS", ij_BOOTSTRAPjs, InJector_bootstrapJS);
    
    var ij_ANGULARjs = "angularskeleton.quickject";
    CommandManager.register("CloudFlare Angular JS", ij_ANGULARjs, InJector_AngularJS);
    
    var ij_CSS = "cssskeleton.quickject";
    CommandManager.register("CSS Reset", ij_CSS, InJector_css);

    var ij_about = "about.quickject";
    CommandManager.register("About Extension", ij_about, InJector_about);

    Menus.addMenu('InJector','quickject.main');
    var menu = Menus.getMenu('quickject.main');
    menu.addMenuItem(ij_HTML);
    menu.addMenuItem(ij_JQUERY);
    menu.addMenuItem(ij_BOOTSTRAPcs);
    menu.addMenuItem(ij_BOOTSTRAPjs);
    menu.addMenuItem(ij_ANGULARjs);
    menu.addMenuItem(ij_CSS);
    menu.addMenuDivider();
    menu.addMenuItem(ij_about);
    
});
